[[pages]]
path = "ğŸ _Home.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "pages/1_ğŸ“…_Context_Calendar.py"
name = "Context Calendar"
icon = ":calendar:"

[[pages]]
path = "pages/2_ğŸ“ˆ_Saturation_Curves.py"
name = "Saturation Curves"
icon = ":chart_with_upwards_trend:"
